name: "php-fpm" 

on:
  workflow_call:
    inputs:
      container-tag:
        required: true
        type: string
        description: 'Container tag'
        default: "latest"
      organisation: 
        type: string
        description: The organisation
      app_url:
        type: string
        description: Application url
      app_key_container:
        type: string
        description: Application key container

    secrets:
      KUBECONFIG:
        required: true
      GIT_CHECKOUT_TOKEN:
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  debug: 
    runs-on: [self-hosted, k8s]
    steps:
      - name: "Show Parameters used" 
        run: |
          echo "container-tag = ${{ inputs.container-tag }}"
          echo "app_url = ${{ inputs.app_url }}"
          echo "app_key_container = ${{ inputs.app_key_container }}"

  php-image-build:

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          
      
      - uses: "ramsey/composer-install@v2"
        with:
          version: '8.1'
          php-version: '8.1'
          dependency-versions: 'locked'
          #composer-options: "--ignore-platform-reqs --optimize-autoloader"
        env:
          #COMPOSER_AUTH: '{"http-basic":  {"myorg.repo.repman.io" : {"username": "token","password": ""}},"github-oauth":   {"github.com": "${{ secrets.GIT_CHECKOUT_TOKEN }}" } }'

      - name: PHP Syntax Checker (Lint) Custom folder
        uses: StephaneBour/actions-php-lint@8.1
        with:
          dir: './docroot/modules/custom'
          
      - name: PHP Syntax Checker (Lint) settings file
        uses: StephaneBour/actions-php-lint@8.1
        with:
          dir: './docroot/sites/default/'

      - name: PHP Syntax Checker (Lint) additional settings files
        uses: StephaneBour/actions-php-lint@8.1
        with:
          dir: './etc/drupal'

      -
        name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/php-fpm/Dockerfile
          push: true
          tags: ghcr.io/${{ inputs.organisation }}/${{ inputs.app_key_container }}:${{ inputs.container-tag }}
