name: "Module Code Sniffer"
on:
  workflow_call:
    secrets:
      GIT_CHECKOUT_TOKEN:
        required: true
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: LINT
        uses: StephaneBour/actions-php-lint@8.1
        with:
          dir: '.'
          
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "tests"

      - uses: php-actions/composer@v6
        if: steps.check_files.outputs.files_exists == 'true'
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.GIT_CHECKOUT_TOKEN }}"} }'

      - name: PHPUnit tests
        if: steps.check_files.outputs.files_exists == 'true'
        uses: php-actions/phpunit@v9
        with:
          configuration: phpunit.xml
          #args: --coverage-text
        env:
          XDEBUG_MODE: coverage
          TEST_NAME: Scarlett
          memory_limit: 256M
